### PR TITLE
add iterate_jobs generator for iterating over finished openQA jobs

### PR DESCRIPTION
**Pull request by garretraziel**
This adds genereator for iterating over finished jobs - so that we could report jobs in `for` cycle as soon as job is finished (and don't wait for all jobs to be finished). Also, thanks to my IDE, there were some (automatic) PEP-8 changes.

### CODE REVIEW

**Comment by okurz** [comment]
you could separate the commit into a simple whitespace cleanup one and one for adding the feature.

**Comment by garretraziel** [comment]
Yep, I pushed whitespace cleanup by mistake, so I've deleted it.

**Comment by okurz** [comment]
+1

**Comment by AdamWill** [comment]
This looks more or less fine. WDYT about dropping `wait_jobs()` in favour of this, either immediately or eventually? The things I've written that use it are check-compose and fedora_openqa_schedule; they should be easy to switch over. @okurz , has SUSE started using this for anything?

I guess I'd propose we merge this perhaps with an edit to the `wait_jobs()` docstring marking it as deprecated, convert the code we know about, then give it a week or two and drop `wait_jobs()`, how does that sound?

**Comment by AdamWill** [comment]
Hmm, also, note that in the most common case - when `fedora_openqa_schedule` is being used to both schedule and report jobs together, rather than the `report` subcommand being used to report the results for a list of job IDs manually - we're actually currently using `wait_build_jobs()` rather than `wait_jobs()`. This was to let us get the dicts for all the jobs in a single API hit, to reduce the likelihood of one of those old 500 errors happening. Also note the thing in the `wait_build_jobs()` docstring about it handing off to `wait_jobs()` is a flat lie, it doesn't do that, it's free-standing. (It used to, but I changed it and forgot to change the docstring).

A couple of things have changed since then; openQA has made changes that make those errors less likely to happen, and I got a change merged upstream which lets you hit up the API for a list of job IDs in a single transaction.

Overall I think I might be inclined to try to refactor this stuff a bit more, I'll take a cut at it this afternoon and send an alternative PR if it looks good.

**Comment by AdamWill** [comment]
So I've pushed my take on this as the branch `iterate-jobs`. It's based off of @garretraziel 's, but with a couple of tweaks.

Mine is intended as a replacement for both `wait_jobs()` and `wait_build_jobs()`, and includes all the capabilities of both - except the ability to operate on an iterable of already-retrieved job dicts, it only takes IDs. We can add the ability to operate on dicts back if necessary but it makes things more complex, and I was no longer actually using it for anything, so I'd like to drop it if no-one else needs it.

I've optimized for simplicity and clarity over efficiency. When using `jobs` rather than `build` we *could* try dropping the IDs of already-done jobs from later queries, but it makes the code a bit more complex and I don't think it's actually worth it, in my quick tests, querying for 100 jobs is almost as fast as querying for 1. We could also jump through some hoops to avoid running `get_latest_jobs()` every time through the loop, but I don't think that's worth it either.

The code for retrieving multiple jobs by ID with a single API query landed in 4.2, so instead of including some painful backwards-compatibility to retrieve the job dicts one at a time for older openQA versions, I decided to just say 'this function needs 4.2 on the server' and use that path unconditionally. I think all real-world openQA deployments are on at least 4.2 now anyway (both of Fedora's are, I'm pretty sure SUSE's is, I dunno for sure what's going on with Mageia but I'm pretty sure they'll be using at least the latest stable).

Can you folks take a look and see what you think? Thanks!

**Comment by garretraziel** [comment]
Yeah, code in `iterate-jobs` looks OK.

**Comment by okurz** [comment]
> @okurz , has SUSE started using this for anything?

@AdamWill I have been with SUSE only for some time so I can only speak for myself right now: So far I only follow all different os-autoinst projects but have not made use of them all or even trying to contribute. openQA-python-client was mentioned to me by a colleague so SUSE knows it exists but probably only a few have tried it. I have not seen a use case where we need it though I have also been thinking about connecting to openQA server instances and gathering data using other clients so openQA-python-client might be suitable :-)

Regarding `iterate-jobs`: **LGTM** although I would probably split up the docstring of the method a bit more, e.g. describe parameters in their own paragraphs. The body of the method IMHO has quite some levels of indentions which I would have preferred to be reduced but I also can not give an immediate hint that will make everything beautiful so you can also just keep it as is.

**Comment by AdamWill** [comment]
Thanks folks! I tweaked a few things here and there and merged the branch to master, so closing this. I agreed with @okurz on the indentation so I figured a way to improve it - we don't need to put the entire 'find jobs to yield and yield them' chunk into `if jobdicts:` to handle the 'no jobs at all yet' case, we just need to avoid the `return` clause in that case. This way we do some needless work on a couple of empty lists when there are no jobdicts, but again, clarity over efficiency seems to be the order of the day here :)

**Comment by AdamWill** [comment]
Note: I've already [changed](https://git.fedorahosted.org/cgit/fedora-qa.git/commit/?id=f2c17e464319544a87a78d7b1bc2844d94b856e6) `check-compose` over to `iterate_jobs`. I've sent a [diff](https://phab.qadevel.cloud.fedoraproject.org/D705) for `openqa_fedora_tools`.

**Pull request closed without merging**
