### PR TITLE
Update python test matrix in CI

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by AdamWill** [comment]
Oh, sorry, I didn't see this when I did #38 . But I do prefer having the note I included in the README in my version...

**Comment by mimi1vx** [comment]
@AdamWill your #39 is better, i overlooked tox config and readme :D

**Comment by AdamWill** [comment]
If you wanna open a new one for the 3.11 and 3.12 changes, that'd be great.

**Comment by mimi1vx** [comment]
@AdamWill  #39 with changes ( 3.11 + 3.12 )

**Pull request closed without merging**
