### PR TITLE
fix tilde quoting to match mojo's

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by AdamWill** [comment]
Just before I merge it, are you sure this is the right way around? You're replacing '~' with '%7E' - it's the opposite way around from the other one.

**Comment by lnussel** [comment]
yes, weird but that's how mojo haves here.

**Comment by AdamWill** [comment]
Merged, thanks.

**Comment by AdamWill** [comment]
A follow up question four and a half years later: why do we need to do this here but not in the openQA client code? https://github.com/os-autoinst/openQA/blob/master/lib/OpenQA/UserAgent.pm#L86 does the %20 substitution, but not this one. Does it happen somewhere in Mojo itself?

**Comment by okurz** [comment]
@kraih maybe you know?

**Comment by kraih** [comment]
Not a clue what this is referring to, Mojolicious does not escape tilde characters.
```
$ perl -Mojo -E 'a("/*whatever" => {text => "Hello World!"})->start' get -v '/foo~b ar'
GET /foo~b%20ar HTTP/1.1
Host: 127.0.0.1:49619
Accept-Encoding: gzip
Content-Length: 0
User-Agent: Mojolicious (Perl)

HTTP/1.1 200 OK
Date: Fri, 28 Feb 2020 11:41:25 GMT
Content-Type: text/html;charset=UTF-8
Content-Length: 12
Server: Mojolicious (Perl)

Hello World!
```

**Pull request closed without merging**
