### PR TITLE
Use pathlib instead of os.path module

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Review by okurz — COMMENTED** [review]
your git commit message is stating what you do but not why. Can you please elaborate in the git commit message

**Comment by AdamWill** [comment]
right, this just seems to be an alternative style really. It's fine if that's what you're into, but I'm not sure I wanna change it just for the sake of it. Also I find the `path / ` syntax kinda hinky tbh...

**Comment by mimi1vx** [comment]
> right, this just seems to be an alternative style really. It's fine if that's what you're into, but I'm not sure I wanna change it just for the sake of it. Also I find the `path / ` syntax kinda hinky tbh...

its faster, pythonic and more readable than `os.path.join(os.path.something(os.path.somethingelse))`

:D but yes +- for this small project is practically only cosmetic change

**Comment by AdamWill** [comment]
Maybe I'm old-fashioned but I think I'm just gonna leave this the way it is till `os.path` gets deprecated or something. :D

**Pull request closed without merging**
