### PR TITLE
Add type hints

### PR DESCRIPTION
**Pull request by dcermak**
This still needs a fix in `src/openqa_client/client.py:133`.

### CODE REVIEW

**Comment by AdamWill** [comment]
I have never really bothered looking at this stuff before, and man, it looks ugly and a lot of work. Yeesh.

**Comment by AdamWill** [comment]
I mean, there are obviously benefits to type hinting, don't get me wrong! I'm interested. It's just a bit, you know, a bit a lot. :D

**Comment by dcermak** [comment]
> Oh boy. This introduces a dependency on newer versions, 

It does not. That's why I pulled in the typing extensions module. If that is too much, then the type hints can be split out into `.pyi` files.

> is very verbose and ugly

verbose: yes, because it encodes a good chunk of the documentation in the types themselves.
ugly: that's your opinion.

> and the commit messages don't tell what the benefit is.
> Sorry, but I would say, don't bother and keep as is but maybe you can convince us with good arguments :D

Very well.

**Comment by okurz** [comment]
@dcermak sorry, I was wrong. Can we reconsider and you reopen your PR :) ?

**Comment by dcermak** [comment]
@okurz here you go: https://github.com/os-autoinst/openQA-python-client/pull/23

**Pull request closed without merging**
