### PR TITLE
Remove waiting state

### PR DESCRIPTION
**Pull request by foursixnine**
WAITING state has been removed from openQA already, and it's no longer needed related to This PR

### CODE REVIEW

**Comment by AdamWill** [comment]
Thanks for the heads-up; but as this is just a *removal* I think it would make sense to leave it a while before removing it, as people (like me) may well still be using the client with older openQA code that still has the state, and I don't think it causes any problems for it to still be around even if the openQA you're working with is new enough that it doesn't have the state.

So, unless you have any objections, I figure we should leave this for a few months and merge it later.

**Comment by coolo** [comment]
As you wish. but note that waiting has always been rare - as everyone knows the interactive mode to be broken :)

**Comment by foursixnine** [comment]
No objections from me either :p

**Comment by AdamWill** [comment]
OK, we can probably merge this now. =)

**Pull request merged**
