### PR TITLE
setup.py: Remove runtime dependency on setuptools

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by AdamWill** [comment]
Thanks, I [recreated this](https://github.com/os-autoinst/openQA-python-client/commit/5b08381211b6ba33a95619a7bb3748b31c7f65f4) as I wound up doing a bunch of other cleanup on setup.py first.

**Comment by jayvdb** [comment]
Very odd, even dropping the Author.

Should wantabe contributors be sending PRs to https://github.com/Mattlk13/openQA-python-client instead ?

**Comment by AdamWill** [comment]
sorry, since it was such a trivial change to a fairly obscure project I didn't figure it'd be a problem. I do apologize, I won't do it again. I don't understand the question - that's a personal fork of this (which is the original) that doesn't seem to have any changes made to it, so what would be the point of sending a PR there?

**Comment by jayvdb** [comment]
Finding and validating a bug, before even submitting a patch, is not trivial. ;-)

I saw https://github.com/os-autoinst/openQA-python-client/commit/5b08381211b6ba33a95619a7bb3748b31c7f65f4 refers to https://github.com/Mattlk13/openQA-python-client/pull/4 - now I see it is bot created.

btw, created https://build.opensuse.org/package/show/home:jayvdb:branches:devel:languages:python/python-openqa-client - ill submit it if you've finished the update spree.

**Comment by AdamWill** [comment]
possibly not yet ;) I'm going to fiddle around with dropping Python 2 support and adopting [PEP-517](https://www.python.org/dev/peps/pep-0517/) today, and might merge that and cut another new release if it works out. I'm only keeping Python 2 support around in case anyone wants to run this on RHEL 7 (I do package builds for EPEL 7), but I don't actually know of anyone who is, and it makes adopting Shiny New Things quite annoying, so I might hang it out on a branch or something.

what bug did you hit that this PR fixes, out of interest? I can't recall why I ever had it in the `install_requires`, it's probably cargo culted from years ago (I've been carting the same `setup.py` around forever), but I can't think offhand of where it'd cause a problem...

what happened is your PR actually inspired me to go clean up `setup.py` in a bunch of other ways, one of which was to drop the spaces around the assignments in the `setup()` call to make pylint happy, which of course meant your commit didn't merge cleanly any more, then I didn't want to hang the change up on asking you to rebase it, so I just recreated it and threw it in on top of the other changes...then I realized I could've merged your fix first and rebased everything else on that quite easily, but didn't quite realize it soon enough :/ sorry again about that.

**Comment by AdamWill** [comment]
oh, I know the openQA devs do keep an eye on this and use it at least sometimes, so they may have an OBS build of it lying around somewhere already. Not sure, though. @okurz , @Martchus , @coolo - any notes?

**Comment by okurz** [comment]
No problem to drop Python 2 support from side of openSUSE . https://build.opensuse.org/package/show/devel:openQA/python-openqa_client is the package in OBS that builds a python3-only variant for all supported distris and versions by now.

**Comment by AdamWill** [comment]
OK, I think I'm mostly done with major tinkering now, 4.0.0 is the modernization release with Python 2 support dropped, PEP-517/518 compliance added and other goodies.

**Pull request closed without merging**
